### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by athas** [SacBase/Stdlib#78]
I have a freshly compiled and (I think) operational `sac2c`.  Now I want to compile the stdlib so I can compile real SAC programs.  The instructions in the README work fine, but I am really confused about the mention that I don't need to install it, as `sac2c` "will be able to find your stdlib build automatically".  How can sac2c possibly know that there is a build of the standard library in a random location on the file system?  It certainly didn't seem to be able to.

Anyway, I did a `make install` (after setting `CMAKE_INSTALL_PREFIX` appropriately), and it *seems* to work now.  Am I missing something?

**Comment by sbscholz** [comment]
sac2c is being configured through resource files typically named sac2crc.
They contain information about paths for all kinds of things like compilers and system libraries.
Amongst other things they also keep paths to sac libraries.
The compiler has one basic file within its installation. But the compiler also searches for further files system wide.
This includes the directory ~/.sac2crc.
When you build any of the github.com/sacbase/ projects, this will leave a file in that directory containing the paths
within your system. On my computer, there is:
```
cat sac2crc.package.stdlib

target stdlib:
TREE_OUTPUTDIR += ":/Volumes/Users/sbs/sacbase/Stdlib/build/lib"
LIB_OUTPUTDIR  += ":/Volumes/Users/sbs/sacbase/Stdlib/build/lib"
LIBS           += " "
```
That is how the magic works :-)

**Comment by athas** [comment]
This is also useful knowledge because it means you can't move the build directory without updating those files.  `sac2c` is not *that* magical.
